const products = [
  {
    id: 1,
    name: "iPhone 16",
    brand: "Apple",
    category: "Mobile",
    price: 79999,
    rating: 4.8,
    reviews: 1850,
    stock: 20,
    discount: 5,
    image: "images/iphone16.jpg",
    ram: "8 GB",
    storage: "256 GB",
    processor: "A18",
    camera: "48 MP",
    battery: "3561 mAh",
    display: '6.1"',
    tags: ["Apple", "5G", "Premium"]
  },
  {
    id: 2,
    name: "iPhone 16 Plus",
    brand: "Apple",
    category: "Mobile",
    price: 89999,
    rating: 4.8,
    reviews: 1530,
    stock: 18,
    discount: 5,
    image: "images/iphone16plus.jpg",
    ram: "8 GB",
    storage: "256 GB",
    processor: "A18",
    camera: "48 MP",
    battery: "4674 mAh",
    display: '6.7"',
    tags: ["Apple", "Large Display"]
  },
  {
    id: 3,
    name: "iPhone 16 Pro",
    brand: "Apple",
    category: "Mobile",
    price: 119999,
    rating: 4.9,
    reviews: 2210,
    stock: 15,
    discount: 3,
    image: "images/iphone16pro.jpg",
    ram: "8 GB",
    storage: "256 GB",
    processor: "A18 Pro",
    camera: "48 MP",
    battery: "3582 mAh",
    display: '6.3"',
    tags: ["Apple", "Pro"]
  },
  {
    id: 4,
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "Mobile",
    price: 144999,
    rating: 4.9,
    reviews: 2485,
    stock: 12,
    discount: 2,
    image: "images/iphone16promax.jpg",
    ram: "8 GB",
    storage: "512 GB",
    processor: "A18 Pro",
    camera: "48 MP",
    battery: "4685 mAh",
    display: '6.9"',
    tags: ["Apple", "Flagship"]
  },
  {
    id: 5,
    name: "iPhone 17",
    brand: "Apple",
    category: "Mobile",
    price: 89999,
    rating: 4.8,
    reviews: 250,
    stock: 25,
    discount: 0,
    image: "images/iphone17.jpg",
    ram: "8 GB",
    storage: "256 GB",
    processor: "A19",
    camera: "48 MP",
    battery: "3900 mAh",
    display: '6.3"',
    tags: ["Apple", "Latest"]
  },
  {
    id: 6,
    name: "Samsung Galaxy S26 Ultra",
    brand: "Samsung",
    category: "Mobile",
    price: 129999,
    rating: 4.9,
    reviews: 980,
    stock: 10,
    discount: 5,
    image: "images/s26ultra.jpg",
    ram: "12 GB",
    storage: "512 GB",
    processor: "Snapdragon 8 Elite",
    camera: "200 MP",
    battery: "5000 mAh",
    display: '6.9"',
    tags: ["Samsung", "Flagship"]
  },
  {
    id: 7,
    name: "Google Pixel 10",
    brand: "Google",
    category: "Mobile",
    price: 79999,
    rating: 4.8,
    reviews: 650,
    stock: 15,
    discount: 5,
    image: "images/pixel10.jpg",
    ram: "12 GB",
    storage: "256 GB",
    processor: "Tensor G5",
    camera: "50 MP",
    battery: "5000 mAh",
    display: '6.3"',
    tags: ["Google", "Camera"]
  },
  {
    id: 8,
    name: "OnePlus 15",
    brand: "OnePlus",
    category: "Mobile",
    price: 69999,
    rating: 4.7,
    reviews: 720,
    stock: 18,
    discount: 8,
    image: "images/oneplus15.jpg",
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8 Elite",
    camera: "50 MP",
    battery: "6000 mAh",
    display: '6.8"',
    tags: ["Gaming"]
  },
  {
    id: 9,
    name: "Nothing Phone 3",
    brand: "Nothing",
    category: "Mobile",
    price: 54999,
    rating: 4.6,
    reviews: 430,
    stock: 20,
    discount: 10,
    image: "images/nothing3.jpg",
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8s Gen4",
    camera: "50 MP",
    battery: "5150 mAh",
    display: '6.7"',
    tags: ["Nothing"]
  },
  {
    id: 10,
    name: "Vivo X300 Ultra",
    brand: "Vivo",
    category: "Mobile",
    price: 94999,
    rating: 4.8,
    reviews: 350,
    stock: 10,
    discount: 4,
    image: "images/vivox300.jpg",
    ram: "16 GB",
    storage: "512 GB",
    processor: "Dimensity 9500",
    camera: "200 MP",
    battery: "6000 mAh",
    display: '6.8"',
    tags: ["Camera"]
  },
  {
    id: 11,
    name: "iPad Air M3",
    brand: "Apple",
    category: "Tablet",
    price: 59999,
    rating: 4.8,
    reviews: 820,
    stock: 20,
    discount: 5,
    image: "images/ipadair.jpg",
    ram: "8 GB",
    storage: "128 GB",
    processor: "M3",
    battery: "7600 mAh",
    display: '11"',
    tags: ["Student"]
  },
  {
    id: 12,
    name: "iPad Pro M4",
    brand: "Apple",
    category: "Tablet",
    price: 99999,
    rating: 4.9,
    reviews: 920,
    stock: 12,
    discount: 3,
    image: "images/ipadpro.jpg",
    ram: "16 GB",
    storage: "256 GB",
    processor: "M4",
    battery: "8160 mAh",
    display: '13"',
    tags: ["Professional"]
  },
  {
    id: 13,
    name: "Samsung Galaxy Tab S11",
    brand: "Samsung",
    category: "Tablet",
    price: 74999,
    rating: 4.8,
    reviews: 530,
    stock: 15,
    discount: 6,
    image: "images/tabs11.jpg",
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8 Elite",
    battery: "10090 mAh",
    display: '11"',
    tags: ["Android"]
  },
  {
    id: 14,
    name: "OnePlus Pad 3",
    brand: "OnePlus",
    category: "Tablet",
    price: 42999,
    rating: 4.7,
    reviews: 310,
    stock: 20,
    discount: 8,
    image: "images/pad3.jpg",
    ram: "12 GB",
    storage: "256 GB",
    processor: "Dimensity 9400",
    battery: "9510 mAh",
    display: '11.6"',
    tags: ["Value"]
  },
  {
    id: 15,
    name: "Lenovo Tab Plus",
    brand: "Lenovo",
    category: "Tablet",
    price: 29999,
    rating: 4.5,
    reviews: 280,
    stock: 18,
    discount: 10,
    image: "images/lenovotab.jpg",
    ram: "8 GB",
    storage: "128 GB",
    processor: "Helio G99",
    battery: "8600 mAh",
    display: '11.5"',
    tags: ["Budget"]
  },
  {
    id: 16,
    name: "Apple Watch Series 10",
    brand: "Apple",
    category: "Smart Watch",
    price: 49999,
    rating: 4.9,
    reviews: 12,
    stock: 3,
    discount: null,
    image: "images/watch10.jpg",
    battery: "18 Hours",
    display: "OLED",
    tags: ["Premium"],
    bluetoothCalling: "Yes"
  },
  {
    id: 17,
    name: "Samsung Galaxy Watch Ultra",
    brand: "Samsung",
    category: "Smart Watch",
    price: 39999,
    rating: 4.8,
    reviews: 10,
    stock: 5,
    discount: null,
    image: "images/watchultra.jpg",
    battery: "100 Hours",
    display: "AMOLED",
    tags: ["Outdoor"],
    bluetoothCalling: "Yes"
  },
  {
    id: 18,
    name: "Google Pixel Watch 4",
    brand: "Google",
    category: "Smart Watch",
    price: 35999,
    rating: 4.7,
    reviews: 15,
    stock: 5,
    discount: null,
    image: "images/pixelwatch4.jpg",
    battery: "48 Hours",
    display: "AMOLED",
    tags: ["Wear OS"],
    bluetoothCalling: "Yes"
  },
  {
    id: 19,
    name: "Noise ColorFit Pro 6",
    brand: "Noise",
    category: "Smart Watch",
    price: 5999,
    rating: 4.5,
    reviews: 40,
    stock: 12,
    discount: null,
    image: "images/noise6.jpg",
    battery: "7 Days",
    display: "AMOLED",
    tags: ["Budget"],
    bluetoothCalling: "Yes"
  },
  {
    id: 20,
    name: "boAt Lunar Pro",
    brand: "boAt",
    category: "Smart Watch",
    price: 3499,
    rating: 4.4,
    reviews: 55,
    stock: 15,
    discount: null,
    image: "images/boatlunar.jpg",
    battery: "7 Days",
    display: "LCD",
    tags: ["Affordable"],
    bluetoothCalling: "Yes"
  },
  {
    id: 21,
    name: "LG Double Door Frost Free",
    brand: "LG",
    category: "Refrigerator",
    price: 38999,
    rating: 4.7,
    reviews: 640,
    stock: 15,
    discount: 8,
    image: "images/lgfridge.jpg",
    tags: ["LG", "Frost Free"],
    starRating: "3 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "260 L"
  },
  {
    id: 22,
    name: "Samsung Bespoke AI Refrigerator",
    brand: "Samsung",
    category: "Refrigerator",
    price: 69999,
    rating: 4.8,
    reviews: 420,
    stock: 8,
    discount: 5,
    image: "images/samsungfridge.jpg",
    tags: ["AI", "Premium"],
    starRating: "3 Star",
    inverter: "Yes",
    warranty: "20 Years",
    capacity: "330 L"
  },
  {
    id: 23,
    name: "Whirlpool IntelliFresh",
    brand: "Whirlpool",
    category: "Refrigerator",
    price: 32999,
    rating: 4.6,
    reviews: 520,
    stock: 12,
    discount: 10,
    image: "images/whirlpoolfridge.jpg",
    tags: ["Convertible"],
    starRating: "2 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "265 L"
  },
  {
    id: 24,
    name: "Haier Convertible Refrigerator",
    brand: "Haier",
    category: "Refrigerator",
    price: 35999,
    rating: 4.6,
    reviews: 310,
    stock: 10,
    discount: 8,
    image: "images/haierfridge.jpg",
    tags: ["Convertible"],
    starRating: "3 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "325 L"
  },
  {
    id: 25,
    name: "Godrej Eon Refrigerator",
    brand: "Godrej",
    category: "Refrigerator",
    price: 28999,
    rating: 4.5,
    reviews: 280,
    stock: 18,
    discount: 12,
    image: "images/godrejfridge.jpg",
    tags: ["Budget"],
    starRating: "2 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "244 L"
  },
  {
    id: 26,
    name: "LG Front Load AI DD",
    brand: "LG",
    category: "Washing Machine",
    price: 42999,
    rating: 4.8,
    reviews: 490,
    stock: 10,
    discount: 8,
    image: "images/lgwm.jpg",
    tags: ["Front Load"],
    starRating: "5 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "8 Kg"
  },
  {
    id: 27,
    name: "Samsung Bespoke AI Washer",
    brand: "Samsung",
    category: "Washing Machine",
    price: 46999,
    rating: 4.8,
    reviews: 350,
    stock: 8,
    discount: 5,
    image: "images/samsungwm.jpg",
    tags: ["AI"],
    starRating: "5 Star",
    inverter: "Yes",
    warranty: "20 Years",
    capacity: "9 Kg"
  },
  {
    id: 28,
    name: "IFB Front Load",
    brand: "IFB",
    category: "Washing Machine",
    price: 38999,
    rating: 4.7,
    reviews: 420,
    stock: 12,
    discount: 10,
    image: "images/ifbwm.jpg",
    tags: ["Premium"],
    starRating: "5 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "8 Kg"
  },
  {
    id: 29,
    name: "Whirlpool Top Load",
    brand: "Whirlpool",
    category: "Washing Machine",
    price: 23999,
    rating: 4.5,
    reviews: 510,
    stock: 15,
    discount: 12,
    image: "images/whirlpoolwm.jpg",
    tags: ["Top Load"],
    starRating: "5 Star",
    inverter: "Yes",
    warranty: "10 Years",
    capacity: "7 Kg"
  },
  {
    id: 30,
    name: "Bosch Front Load",
    brand: "Bosch",
    category: "Washing Machine",
    price: 44999,
    rating: 4.8,
    reviews: 300,
    stock: 8,
    discount: 6,
    image: "images/boschwm.jpg",
    tags: ["German Tech"],
    starRating: "5 Star",
    inverter: "Yes",
    warranty: "12 Years",
    capacity: "9 Kg"
  },
  {
    id: 31,
    name: "LG Dual Inverter AC",
    brand: "LG",
    category: "Air Conditioner",
    price: 44999,
    rating: 4.8,
    reviews: 610,
    stock: 12,
    discount: 8,
    image: "images/lgac.jpg",
    tags: ["Dual Inverter"],
    starRating: "5 Star",
    inverter: "Yes",
    ton: "1.5 Ton",
    warranty: "10 Years"
  },
  {
    id: 32,
    name: "Daikin Inverter AC",
    brand: "Daikin",
    category: "Air Conditioner",
    price: 48999,
    rating: 4.8,
    reviews: 470,
    stock: 10,
    discount: 5,
    image: "images/daikinac.jpg",
    tags: ["Premium"],
    starRating: "5 Star",
    inverter: "Yes",
    ton: "1.5 Ton",
    warranty: "10 Years"
  },
  {
    id: 33,
    name: "Samsung WindFree AI AC",
    brand: "Samsung",
    category: "Air Conditioner",
    price: 52999,
    rating: 4.8,
    reviews: 320,
    stock: 8,
    discount: 5,
    image: "images/samsungac.jpg",
    tags: ["AI"],
    starRating: "5 Star",
    inverter: "Yes",
    ton: "1.5 Ton",
    warranty: "10 Years"
  },
  {
    id: 34,
    name: "Blue Star Inverter AC",
    brand: "Blue Star",
    category: "Air Conditioner",
    price: 42999,
    rating: 4.7,
    reviews: 380,
    stock: 10,
    discount: 10,
    image: "images/bluestarac.jpg",
    tags: ["Energy Saving"],
    starRating: "5 Star",
    inverter: "Yes",
    ton: "1.5 Ton",
    warranty: "10 Years"
  },
  {
    id: 35,
    name: "Voltas Adjustable Inverter AC",
    brand: "Voltas",
    category: "Air Conditioner",
    price: 39999,
    rating: 4.6,
    reviews: 450,
    stock: 14,
    discount: 12,
    image: "images/voltasac.jpg",
    tags: ["Budget"],
    starRating: "3 Star",
    inverter: "Yes",
    ton: "1.5 Ton",
    warranty: "10 Years"
  },
  {
    id: 36,
    name: "LG NeoChef",
    brand: "LG",
    category: "Microwave",
    price: 14999,
    rating: 4.7,
    reviews: 290,
    stock: 15,
    discount: 8,
    image: "images/lgmicro.jpg",
    tags: ["Convection"],
    warranty: "1 Year",
    capacity: "28 L"
  },
  {
    id: 37,
    name: "Samsung Grill Microwave",
    brand: "Samsung",
    category: "Microwave",
    price: 12999,
    rating: 4.6,
    reviews: 260,
    stock: 18,
    discount: 10,
    image: "images/samsungmicro.jpg",
    tags: ["Grill"],
    warranty: "1 Year",
    capacity: "28 L"
  },
  {
    id: 38,
    name: "IFB Convection Microwave",
    brand: "IFB",
    category: "Microwave",
    price: 15999,
    rating: 4.8,
    reviews: 310,
    stock: 10,
    discount: 6,
    image: "images/ifbmicro.jpg",
    tags: ["Convection"],
    warranty: "1 Year",
    capacity: "30 L"
  },
  {
    id: 39,
    name: "Panasonic Convection Oven",
    brand: "Panasonic",
    category: "Microwave",
    price: 13999,
    rating: 4.6,
    reviews: 220,
    stock: 12,
    discount: 8,
    image: "images/panasonicmicro.jpg",
    tags: ["Multi Cook"],
    warranty: "1 Year",
    capacity: "27 L"
  },
  {
    id: 40,
    name: "Whirlpool Magicook",
    brand: "Whirlpool",
    category: "Microwave",
    price: 10999,
    rating: 4.5,
    reviews: 340,
    stock: 20,
    discount: 12,
    image: "images/whirlpoolmicro.jpg",
    tags: ["Budget"],
    warranty: "1 Year",
    capacity: "25 L"
  }
];
